version: '3.9'

services:
 
  db:
    container_name: db
    image: postgres
    restart: always
    ports:
      - 5431:5432
    env_file:
      - ./api/.env
    expose:
      - 5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -q -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s

  api:
    container_name: customer_base_api
    build: 
      context: ./api
      dockerfile: Dockerfile
    ports:
      - 4000:4000
    env_file:
      - ./api/.env
    depends_on:
      db:
        condition: service_healthy
    command: yarn start:migrate:dev
    volumes:
      - /app/node_modules
      - ./api:/app
 
  client:
    container_name: client
    stdin_open: true
    build: 
      context: ./client
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - /app/node_modules
      - ./client:/app